import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';

const roboto = Roboto_Slab({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'My Store',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={roboto.className}>{children}</body>
            </html>
        </ClerkProvider>
    );
}
