import type { Metadata } from 'next';
import { Roboto_Slab } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';
import { Suspense } from 'react';
import Loading from './loading';
import Providers from '@/lib/redux/Provider';

const roboto = Roboto_Slab({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'My Store',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${roboto.className} overflow-x-hidden`}>
                    <Suspense fallback={<Loading />}>
                        <Providers>{children}</Providers>
                    </Suspense>
                </body>
            </html>
        </ClerkProvider>
    );
}
